### PR TITLE
Phrasal verbs functionality

### PR DESCRIPTION
**Pull request by Arelaxe**

### CODE REVIEW

**Comment by d-ivashchuk** [comment]
Not sure what you did here. Do you mind explaining a little bit?

**Comment by Arelaxe** [comment]
I added two English phrasal verbs in ./src/container/data/phrasalVerbs.ts

**Comment by d-ivashchuk** [comment]
>I added two English phrasal verbs in ./src/container/data/phrasalVerbs.ts

@Arelaxe I think you’ve did pull request for the wrong branch. Do you mind changing it, so it would be phrasal-verbs-functionality? Thanks!

**Comment by Arelaxe** [comment]
@d-ivashchuk huk I've done it, could you check it?

**Pull request closed without merging**
