### PR TITLE
added dutch translation

### PR DESCRIPTION
**Pull request by fpkmatthi**
I changed **pastTense** to **pastTenseSingular** and added **pastTensePlural**.
If you'd rather keep **pastTense** instead of **pastTenseSingular** you can use sed in a terminal like this:
```bash
sed -E 's/pastTenseSingular(.*)/pastTense\1/g' data-nl.ts
```

### CODE REVIEW

**Comment by d-ivashchuk** [comment]
@fpkmatthi Great job! Thanks! So some of them don't have a plural form, and you left the initial structure there, right?

**Comment by fpkmatthi** [comment]
my bad, I forgot to merge 2 files together when I was testing scripts on the other file. I'll fix it righ away.

**Comment by d-ivashchuk** [comment]
Ok, thanks for your input!

**Comment by fpkmatthi** [comment]
All translations should be complete now. I used the same structure as in the file with german translations.
I only sorted the blocks.

**Comment by d-ivashchuk** [comment]
Cool, I  will look trough it to fix some Russian translations and merge it in the next days!

**Pull request merged**
